import { useState, useEffect, useMemo } from 'react'
import { useRouter } from 'next/router'
import { motion, AnimatePresence } from 'framer-motion'
import Link from 'next/link'
import PlaybookTabs from './PlaybookTabs'
import CldImage from '../ui/CldImage'

const HERO_BG = 'https://res.cloudinary.com/dlifgfg6m/image/upload/v1777458845/FAQ_Banner_Articles_Banner_1441x518_x2_w9eods.webp'
const CTA_BG = 'https://res.cloudinary.com/dlifgfg6m/image/upload/v1774941574/Rectangle_8_ymxlxb.jpg'

const SIDEBAR_CATEGORIES = [
  {
    label: 'Getting Started',
    items: ['Platform', 'Plans & Billing', 'AI & Output', 'Collaboration', 'Support'],
  },
]

const FAQ_DATA = {
  Platform: [
    {
      id: 'toolkit-included',
      question: 'What Toolkit are included in MANIFESTR?',
      searchable:
        'deck briefcase strategist cost ctrl wordsmith design studio huddle analyzer toolkit the vault',
      defaultOpen: true,
      answer: (
        <div className="flex flex-col gap-[16px] text-[15px] leading-[24px] text-[#52525b]" style={{ fontFamily: 'Inter, sans-serif' }}>
          <p>MANIFESTR includes a suite of AI-powered Toolkit that cover your whole workflow:</p>
          <ul className="flex flex-col gap-[12px] pl-[20px] list-disc">
            <li>
              <span className="font-semibold text-[#18181b]">THE DECK</span>
              {' - Instantly create on-brand presentations for pitches and reports.'}
            </li>
            <li>
              <span className="font-semibold text-[#18181b]">BRIEFCASE</span>
              {' - Draft strategies, timelines, recaps, and proposals.'}
            </li>
            <li>
              <span className="font-semibold text-[#18181b]">THE STRATEGIST</span>
              {' - Turn ideas and inputs into insight-driven frameworks.'}
            </li>
            <li>
              <span className="font-semibold text-[#18181b]">COST CTRL</span>
              {' - Build budgets, margins, and financial summaries.'}
            </li>
            <li>
              <span className="font-semibold text-[#18181b]">WORDSMITH</span>
              {' - Write persuasive copy, headlines, and localizations.'}
            </li>
            <li>
              <span className="font-semibold text-[#18181b]">DESIGN STUDIO</span>
              {' - Generate visuals, mockups, and brand graphics.'}
            </li>
            <li>
              <span className="font-semibold text-[#18181b]">THE HUDDLE</span>
              {' - Auto-generate agendas, summaries, and discussion guides.'}
            </li>
            <li>
              <span className="font-semibold text-[#18181b]">THE ANALYZER</span>
              {' - Turn data into charts, graphs, and summaries.'}
            </li>
          </ul>
        </div>
      ),
    },
    {
      id: 'deck-vs-briefcase',
      question: "What's the difference between THE DECK, BRIEFCASE, and THE STRATEGIST?",
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          THE DECK is for creating polished presentations and pitch decks. BRIEFCASE is for drafting written documents like strategies, proposals, and recaps. THE STRATEGIST is for building frameworks, competitive analyses, and directional roadmaps. They work best together — Strategist to plan, Briefcase to write, and Deck to present.
        </p>
      ),
    },
    {
      id: 'vault',
      question: 'What is The Vault?',
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          The Vault is your personal asset library inside MANIFESTR. It stores your brand materials, templates, previous outputs, and reusable components so you can access and repurpose them across all your projects.
        </p>
      ),
    },
    {
      id: 'collab-hub',
      question: "What's the Collaboration Hub?",
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          The Collaboration Hub is where your team works together in real time. You can share workspaces, co-edit documents, leave comments, and manage access permissions for each team member.
        </p>
      ),
    },
    {
      id: 'style-guide',
      question: "What's the Style Guide and how does it work?",
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          The Style Guide lets you define your brand&apos;s fonts, colors, tone of voice, and visual rules. Once set up, every output generated by MANIFESTR will automatically apply your brand guidelines — keeping everything consistent.
        </p>
      ),
    },
    {
      id: 'multi-brand',
      question: 'Can I use different style guides for different clients or brands?',
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          Yes. You can create and save multiple Style Guides and switch between them per project. This is ideal for agencies or freelancers managing multiple client brands.
        </p>
      ),
    },
    {
      id: 'notifications',
      question: 'Can I turn notifications off?',
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          Yes. Head to your account settings and navigate to Notifications. You can toggle off individual notification types or silence all notifications at once.
        </p>
      ),
    },
    {
      id: 'playbook',
      question: 'What is THE PLAYBOOK?',
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          THE PLAYBOOK is your help center and learning hub. It includes knowledge base articles, demo videos, a glossary, product update notes, FAQs, and a support ticket system.
        </p>
      ),
    },
    {
      id: 'backstage',
      question: 'What is Backstage Access?',
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          Backstage Access is an exclusive membership tier that unlocks early access to new features, beta tools, and priority support. It&apos;s available on select MANIFESTR plans.
        </p>
      ),
    },
    {
      id: 'free-trial',
      question: 'Do you offer free trials or demos?',
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          Yes, MANIFESTR offers a free trial so you can explore the platform before committing. You can also book a guided demo with our team to see the full toolkit in action.
        </p>
      ),
    },
    {
      id: 'custom-templates',
      question: 'Do you support custom templates and my own branding?',
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          Absolutely. You can upload your own templates, set up your brand style guide, and use your own assets across all MANIFESTR tools. Your brand stays consistent by default.
        </p>
      ),
    },
    {
      id: 'file-types',
      question: 'What file types can I export?',
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          MANIFESTR supports exporting to PDF, PPTX, DOCX, PNG, and more depending on the tool. Export options vary by output type and are accessible from every project.
        </p>
      ),
    },
  ],
  'Plans & Billing': [],
  'AI & Output': [],
  Collaboration: [],
  Support: [],
}

function matchesFaqQuery(q, faq) {
  const s = q.trim().toLowerCase()
  if (!s) return true
  if (faq.question.toLowerCase().includes(s)) return true
  if (faq.searchable && faq.searchable.toLowerCase().includes(s)) return true
  return false
}

function ChevronIcon({ open, className = '' }) {
  return (
    <svg
      className={`h-5 w-5 shrink-0 transition-transform duration-300 ${open ? 'rotate-180' : ''} ${className}`}
      fill="none"
      stroke="currentColor"
      viewBox="0 0 24 24"
    >
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
    </svg>
  )
}

export default function PlaybookFAQs() {
  const router = useRouter()
  const [activeCategory, setActiveCategory] = useState('Platform')
  const [openIds, setOpenIds] = useState(() => {
    const defaultOpen = {}
    FAQ_DATA['Platform'].forEach((faq) => {
      if (faq.defaultOpen) defaultOpen[faq.id] = true
    })
    return defaultOpen
  })
  const [searchQuery, setSearchQuery] = useState('')
  const [mobileCatOpen, setMobileCatOpen] = useState(false)

  useEffect(() => {
    if (!router.isReady) return
    const raw = router.query.q
    if (raw === undefined) {
      setSearchQuery('')
      return
    }
    if (Array.isArray(raw)) setSearchQuery(raw[0] ?? '')
    else if (typeof raw === 'string') setSearchQuery(raw)
  }, [router.isReady, router.query.q])

  const filteredFaqs = useMemo(() => {
    const q = searchQuery.trim()
    if (!q) return FAQ_DATA[activeCategory] || []
    return Object.values(FAQ_DATA)
      .flat()
      .filter((f) => matchesFaqQuery(q, f))
  }, [searchQuery, activeCategory])

  function applySearch(e) {
    e?.preventDefault()
    const q = searchQuery.trim()
    const path = q ? `/playbook/faqs?q=${encodeURIComponent(q)}` : '/playbook/faqs'
    router.push(path, undefined, { shallow: true })
  }

  function toggleFaq(id) {
    setOpenIds((prev) => ({ ...prev, [id]: !prev[id] }))
  }

  function handleCategoryChange(cat) {
    setActiveCategory(cat)
    const defaults = {}
    ;(FAQ_DATA[cat] || []).forEach((faq) => {
      if (faq.defaultOpen) defaults[faq.id] = true
    })
    setOpenIds(defaults)
    setSearchQuery('')
    if (router.isReady && router.query.q) {
      router.push('/playbook/faqs', undefined, { shallow: true })
    }
    setMobileCatOpen(false)
  }

  return (
    <>
      {/* ─── Breadcrumb ─── */}
      <div className="w-full bg-white border-t border-b border-[#e5e7eb] px-6 md:px-[80px]">
        <div className="flex items-center gap-[8px] h-[54px]">
          <Link
            href="/playbook"
            className="text-[14px] leading-[21px] text-[#52525b] hover:underline"
            style={{ fontFamily: 'Inter, sans-serif' }}
          >
            Playbook
          </Link>
          <svg className="w-[16px] h-[16px] text-[#52525b]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
          </svg>
          <span
            className="text-[14px] leading-[21px] font-medium text-[#18181b]"
            style={{ fontFamily: 'Inter, sans-serif' }}
          >
            FAQ
          </span>
        </div>
      </div>

      {/* ─── Hero ─── */}
      <section className="relative flex h-[400px] w-full items-center justify-center overflow-hidden px-6 md:h-[518px] md:px-[80px]">
        <div aria-hidden="true" className="pointer-events-none absolute inset-0">
          <CldImage src={HERO_BG} alt="" className="absolute h-full w-full object-cover" />
          <div className="absolute inset-0 bg-black/20" />
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7 }}
          className="relative z-10 flex w-full max-w-[560px] flex-col items-center gap-6 md:gap-8"
        >
          <div className="flex max-w-[603px] flex-col items-center gap-5 text-center md:gap-6">
            <h1 className="text-center text-[36px] leading-[1.1] tracking-[-0.72px] text-white md:text-[72px] md:leading-[90px] md:tracking-[-1.44px]">
              <span style={{ fontFamily: "'Hanken Grotesk', sans-serif", fontWeight: 700 }}>
                Frequently Asked{' '}
              </span>
              <span style={{ fontFamily: "'IvyPresto Headline', serif", fontWeight: 600, fontStyle: 'italic' }}>
                Questions
              </span>
            </h1>
            <p
              className="text-center text-[16px] leading-[24px] text-white md:text-[18px] md:leading-[28px]"
              style={{ fontFamily: 'Inter, sans-serif', fontWeight: 400 }}
            >
              Common questions, answered. Platform, plans, AI, collaboration and support.
            </p>
          </div>

          <div className="flex w-full max-w-[449px] flex-col items-center gap-5">
            <form
              onSubmit={applySearch}
              className="flex w-full items-center gap-2 rounded-md border border-[#d5d7da] bg-white px-3 py-2.5 shadow-[0px_1px_2px_0px_rgba(10,13,18,0.05)] md:px-3.5"
            >
              <svg className="h-5 w-5 shrink-0 text-[#71717a]" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden>
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
              <input
                name="q"
                type="search"
                autoComplete="off"
                placeholder="Search questions & topics"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="min-w-0 flex-1 bg-transparent text-[16px] leading-6 text-[#18181b] outline-none placeholder:text-[#71717a]"
                style={{ fontFamily: 'Inter, sans-serif' }}
              />
              <button
                type="submit"
                className="shrink-0 rounded bg-[#18181b] px-2.5 py-1.5 text-[13px] font-medium text-white hover:bg-[#27272a] md:px-3"
                style={{ fontFamily: 'Inter, sans-serif' }}
              >
                Search
              </button>
            </form>

            <Link
              href="/signup"
              className="inline-flex h-11 w-full max-w-[449px] items-center justify-center rounded-[6px] bg-white px-6 text-[14px] font-medium leading-5 text-[#0d0d0d] transition-colors hover:bg-[#f4f4f5] sm:w-auto"
              style={{ fontFamily: 'Inter, sans-serif' }}
            >
              Enter MANIFESTR
            </Link>
          </div>
        </motion.div>
      </section>

      {/* ─── Tabs ─── */}
      <PlaybookTabs />

      {/* ─── Mobile category dropdown ─── */}
      {!searchQuery && (
        <div className="md:hidden w-full bg-white border-b border-[#d0d5dd]">
          <button
            onClick={() => setMobileCatOpen(!mobileCatOpen)}
            className="w-full flex items-center justify-between px-[16px] py-[12px]"
          >
            <span
              className="text-[14px] leading-[20px] font-semibold text-[#0a0d14] tracking-[-0.14px]"
              style={{ fontFamily: 'Inter, sans-serif' }}
            >
              Getting Started
            </span>
            <ChevronIcon open={mobileCatOpen} />
          </button>
          <AnimatePresence>
            {mobileCatOpen && (
              <motion.div
                initial={{ height: 0 }}
                animate={{ height: 'auto' }}
                exit={{ height: 0 }}
                transition={{ duration: 0.2 }}
                className="overflow-hidden"
              >
                <div className="flex flex-col border-t border-[#e5e7eb]">
                  {SIDEBAR_CATEGORIES[0].items.map((item) => (
                    <button
                      key={item}
                      onClick={() => handleCategoryChange(item)}
                      className={`text-left px-[16px] py-[12px] text-[14px] leading-[20px] transition-colors ${
                        activeCategory === item
                          ? 'font-semibold text-[#1e293b] bg-[#f9fafb]'
                          : 'font-medium text-[#475569] hover:bg-[#f9fafb]'
                      }`}
                      style={{ fontFamily: 'Inter, sans-serif' }}
                    >
                      {item}
                    </button>
                  ))}
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      )}

      {/* ─── FAQ Content ─── */}
      <section className="w-full bg-white px-6 md:px-[112px] py-[24px] md:py-[96px]">
        {/* Mobile section title */}
        {!searchQuery && (
          <div className="md:hidden mb-[12px]">
            <h2
              className="text-[30px] leading-[38px] text-[#1b1b1f]"
              style={{ fontFamily: "'Hanken Grotesk', sans-serif", fontWeight: 500 }}
            >
              {activeCategory}
            </h2>
          </div>
        )}

        <div className="flex gap-[64px] items-start">
          {/* Sidebar — desktop only */}
          {!searchQuery && (
            <aside className="hidden md:flex w-[280px] shrink-0 flex-col gap-[16px]">
              {SIDEBAR_CATEGORIES.map((cat) => (
                <div key={cat.label} className="flex flex-col gap-[16px]">
                  <p
                    className="text-[14px] leading-[20px] font-bold text-[#020617] tracking-[-0.084px]"
                    style={{ fontFamily: "'Plus Jakarta Sans', sans-serif" }}
                  >
                    {cat.label}
                  </p>
                  <div className="flex flex-col">
                    {cat.items.map((item) => {
                      const isActive = activeCategory === item
                      return (
                        <button
                          key={item}
                          onClick={() => handleCategoryChange(item)}
                          className={`flex items-center min-h-[48px] px-[16px] py-[12px] border-l-2 transition-colors text-left w-full ${
                            isActive
                              ? 'border-[#020617] bg-white'
                              : 'border-[#cbd5e1] bg-white hover:border-[#94a3b8]'
                          }`}
                        >
                          <span
                            className={`text-[16px] leading-[22px] tracking-[-0.112px] ${
                              isActive ? 'font-semibold text-[#1e293b]' : 'font-medium text-[#475569]'
                            }`}
                            style={{ fontFamily: 'Inter, sans-serif' }}
                          >
                            {item}
                          </span>
                        </button>
                      )
                    })}
                  </div>
                </div>
              ))}
            </aside>
          )}

          {/* FAQ list */}
          <div className={`flex flex-col gap-[16px] ${searchQuery ? 'w-full' : 'flex-1 min-w-0'}`}>
            {filteredFaqs.length === 0 ? (
              <p
                className="text-[16px] text-[#475569] py-[40px] text-center"
                style={{ fontFamily: 'Inter, sans-serif' }}
              >
                No FAQs found for your search.
              </p>
            ) : (
              filteredFaqs.map((faq, i) => {
                const isOpen = !!openIds[faq.id]

                return (
                  <motion.div
                    key={faq.id}
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.3, delay: i * 0.04 }}
                    className={`overflow-hidden rounded-[12px] border p-5 transition-colors md:px-6 md:py-5 ${
                      isOpen
                        ? 'border-[#e2e8f0] bg-[#f4f4f4]'
                        : 'border-[#c6c8d0] bg-white'
                    } `}
                  >
                    <button
                      type="button"
                      onClick={() => toggleFaq(faq.id)}
                      className="flex w-full items-start gap-3 text-left md:gap-6"
                    >
                      <span
                        className={`flex-1 font-medium ${
                          isOpen
                            ? 'text-[16px] leading-[26px] text-[#1e293b] md:text-[18px] md:leading-[28px]'
                            : 'text-[14px] leading-[24px] text-[#0f172a] md:text-[18px] md:leading-[28px]'
                        }`}
                        style={{ fontFamily: 'Inter, sans-serif' }}
                      >
                        {faq.question}
                      </span>
                      <span className="mt-1 shrink-0 text-[#64748b]">
                        <ChevronIcon open={isOpen} />
                      </span>
                    </button>

                    <AnimatePresence initial={false}>
                      {isOpen && (
                        <motion.div
                          key="content"
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: 'auto', opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          transition={{ duration: 0.25, ease: 'easeInOut' }}
                          className="overflow-hidden"
                        >
                          <div className="pt-[12px]">{faq.answer}</div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </motion.div>
                )
              })
            )}
          </div>
        </div>
      </section>

      {/* ─── Need More Help? ─── */}
      <section className="relative h-[380px] w-full overflow-hidden md:h-[414px]">
        <CldImage src={CTA_BG} alt="" className="absolute inset-0 h-full w-full object-cover" />
        <div className="absolute inset-0 flex items-center justify-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="flex flex-col items-center gap-[30px] px-6 text-center"
          >
            <div className="flex flex-col items-center gap-[16px]">
              <h2 className="text-[36px] leading-tight text-black md:text-[60px] md:leading-[72px] md:tracking-[-1.2px]">
                <span style={{ fontFamily: "'Hanken Grotesk', sans-serif", fontWeight: 700 }}>Need More </span>
                <span style={{ fontFamily: "'IvyPresto Headline', serif", fontWeight: 600, fontStyle: 'italic' }}>Help?</span>
              </h2>
              <p
                className="max-w-[603px] text-[16px] leading-[24px] text-[#52525b]"
                style={{ fontFamily: 'Inter, sans-serif' }}
              >
                {"Can't find what you're looking for? Our support team is here to help you succeed with MANIFESTR."}
              </p>
            </div>
            <Link
              href="/playbook/submit-ticket"
              className="inline-flex h-[44px] items-center justify-center rounded-[6px] bg-[#18181b] px-4 text-[14px] font-medium leading-5 text-white transition-colors hover:bg-[#27272a]"
              style={{ fontFamily: 'Inter, sans-serif' }}
            >
              Submit a Support Ticket
            </Link>
          </motion.div>
        </div>
      </section>
    </>
  )
}
