import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import Link from 'next/link'
import PlaybookTabs from './PlaybookTabs'

const HERO_BG = 'https://www.figma.com/api/mcp/asset/7cae06a8-e177-41c5-b754-05b6ddbaa753'

const SIDEBAR_CATEGORIES = [
  {
    label: 'Getting Started',
    items: ['Platform', 'Plans & Billing', 'AI & Output', 'Collaboration', 'Support'],
  },
]

const FAQ_DATA = {
  Platform: [
    {
      id: 'toolkit-included',
      question: 'What Toolkit are included in MANIFESTR?',
      defaultOpen: true,
      answer: (
        <div className="flex flex-col gap-[16px] text-[14px] leading-[20px] text-[#cacaca]" style={{ fontFamily: 'Inter, sans-serif' }}>
          <p>MANIFESTR includes a suite of AI-powered Toolkit that cover your whole workflow:</p>
          <ul className="list-disc pl-[20px] flex flex-col gap-[12px]">
            <li>
              <span className="font-semibold text-white">THE DECK</span>
              {' - Instantly create on-brand presentations for pitches and reports.'}
            </li>
            <li>
              <span className="font-semibold text-white">BRIEFCASE</span>
              {' - Draft strategies, timelines, recaps, and proposals.'}
            </li>
            <li>
              <span className="font-semibold text-white">THE STRATEGIST</span>
              {' - Turn ideas and inputs into insight-driven frameworks.'}
            </li>
            <li>
              <span className="font-semibold text-white">COST CTRL</span>
              {' - Build budgets, margins, and financial summaries.'}
            </li>
            <li>
              <span className="font-semibold text-white">WORDSMITH</span>
              {' - Write persuasive copy, headlines, and localizations.'}
            </li>
            <li>
              <span className="font-semibold text-white">DESIGN STUDIO</span>
              {' - Generate visuals, mockups, and brand graphics.'}
            </li>
            <li>
              <span className="font-semibold text-white">THE HUDDLE</span>
              {' - Auto-generate agendas, summaries, and discussion guides.'}
            </li>
            <li>
              <span className="font-semibold text-white">THE ANALYZER</span>
              {' - Turn data into charts, graphs, and summaries.'}
            </li>
          </ul>
        </div>
      ),
    },
    {
      id: 'deck-vs-briefcase',
      question: "What's the difference between THE DECK, BRIEFCASE, and THE STRATEGIST?",
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          THE DECK is for creating polished presentations and pitch decks. BRIEFCASE is for drafting written documents like strategies, proposals, and recaps. THE STRATEGIST is for building frameworks, competitive analyses, and directional roadmaps. They work best together — Strategist to plan, Briefcase to write, and Deck to present.
        </p>
      ),
    },
    {
      id: 'vault',
      question: 'What is The Vault?',
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          The Vault is your personal asset library inside MANIFESTR. It stores your brand materials, templates, previous outputs, and reusable components so you can access and repurpose them across all your projects.
        </p>
      ),
    },
    {
      id: 'collab-hub',
      question: "What's the Collaboration Hub?",
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          The Collaboration Hub is where your team works together in real time. You can share workspaces, co-edit documents, leave comments, and manage access permissions for each team member.
        </p>
      ),
    },
    {
      id: 'style-guide',
      question: "What's the Style Guide and how does it work?",
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          The Style Guide lets you define your brand&apos;s fonts, colors, tone of voice, and visual rules. Once set up, every output generated by MANIFESTR will automatically apply your brand guidelines — keeping everything consistent.
        </p>
      ),
    },
    {
      id: 'multi-brand',
      question: 'Can I use different style guides for different clients or brands?',
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          Yes. You can create and save multiple Style Guides and switch between them per project. This is ideal for agencies or freelancers managing multiple client brands.
        </p>
      ),
    },
    {
      id: 'notifications',
      question: 'Can I turn notifications off?',
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          Yes. Head to your account settings and navigate to Notifications. You can toggle off individual notification types or silence all notifications at once.
        </p>
      ),
    },
    {
      id: 'playbook',
      question: 'What is THE PLAYBOOK?',
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          THE PLAYBOOK is your help center and learning hub. It includes knowledge base articles, demo videos, a glossary, product update notes, FAQs, and a support ticket system.
        </p>
      ),
    },
    {
      id: 'backstage',
      question: 'What is Backstage Access?',
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          Backstage Access is an exclusive membership tier that unlocks early access to new features, beta tools, and priority support. It&apos;s available on select MANIFESTR plans.
        </p>
      ),
    },
    {
      id: 'free-trial',
      question: 'Do you offer free trials or demos?',
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          Yes, MANIFESTR offers a free trial so you can explore the platform before committing. You can also book a guided demo with our team to see the full toolkit in action.
        </p>
      ),
    },
    {
      id: 'custom-templates',
      question: 'Do you support custom templates and my own branding?',
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          Absolutely. You can upload your own templates, set up your brand style guide, and use your own assets across all MANIFESTR tools. Your brand stays consistent by default.
        </p>
      ),
    },
    {
      id: 'file-types',
      question: 'What file types can I export?',
      answer: (
        <p className="text-[15px] leading-[24px] text-[#475569]" style={{ fontFamily: 'Inter, sans-serif' }}>
          MANIFESTR supports exporting to PDF, PPTX, DOCX, PNG, and more depending on the tool. Export options vary by output type and are accessible from every project.
        </p>
      ),
    },
  ],
  'Plans & Billing': [],
  'AI & Output': [],
  Collaboration: [],
  Support: [],
}

function ChevronIcon({ open }) {
  return (
    <svg
      className={`w-[20px] h-[20px] shrink-0 transition-transform duration-300 ${open ? 'rotate-180' : ''}`}
      fill="none"
      stroke="currentColor"
      viewBox="0 0 24 24"
    >
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
    </svg>
  )
}

export default function PlaybookFAQs() {
  const [activeCategory, setActiveCategory] = useState('Platform')
  const [openIds, setOpenIds] = useState(() => {
    const defaultOpen = {}
    FAQ_DATA['Platform'].forEach((faq) => {
      if (faq.defaultOpen) defaultOpen[faq.id] = true
    })
    return defaultOpen
  })
  const [searchQuery, setSearchQuery] = useState('')

  const faqs = FAQ_DATA[activeCategory] || []

  const filteredFaqs = searchQuery.trim()
    ? Object.values(FAQ_DATA)
        .flat()
        .filter((f) =>
          f.question.toLowerCase().includes(searchQuery.toLowerCase())
        )
    : faqs

  function toggleFaq(id) {
    setOpenIds((prev) => ({ ...prev, [id]: !prev[id] }))
  }

  function handleCategoryChange(cat) {
    setActiveCategory(cat)
    const defaults = {}
    ;(FAQ_DATA[cat] || []).forEach((faq) => {
      if (faq.defaultOpen) defaults[faq.id] = true
    })
    setOpenIds(defaults)
    setSearchQuery('')
  }

  return (
    <>
      {/* ─── Breadcrumb ─── */}
      <div className="w-full bg-white border-t border-b border-[#e5e7eb] px-6 md:px-[80px]">
        <div className="flex items-center gap-[8px] h-[54px]">
          <Link
            href="/playbook"
            className="text-[14px] leading-[21px] text-[#52525b] hover:underline"
            style={{ fontFamily: 'Inter, sans-serif' }}
          >
            Playbook
          </Link>
          <svg className="w-[16px] h-[16px] text-[#52525b]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
          </svg>
          <span
            className="text-[14px] leading-[21px] font-medium text-[#18181b]"
            style={{ fontFamily: 'Inter, sans-serif' }}
          >
            FAQ
          </span>
        </div>
      </div>

      {/* ─── Hero ─── */}
      <section className="relative w-full h-[518px] flex items-center justify-center overflow-hidden">
        <div aria-hidden="true" className="absolute inset-0 pointer-events-none">
          <img src={HERO_BG} alt="" className="absolute w-full h-full object-cover" />
          <div className="absolute inset-0 bg-black/17" />
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7 }}
          className="relative z-10 flex flex-col items-center gap-[44px]"
        >
          <div className="flex flex-col items-center gap-[14px] text-center">
            <h1
              className="text-[42px] md:text-[60px] leading-tight md:leading-[72px] tracking-[-1.2px] text-white"
            >
              <span style={{ fontFamily: "'Hanken Grotesk', sans-serif", fontWeight: 700 }}>
                Frequently Asked{' '}
              </span>
              <span style={{ fontFamily: "'IvyPresto Headline', serif", fontWeight: 600, fontStyle: 'italic' }}>
                Questions
              </span>
            </h1>
            <p
              className="text-[16px] leading-[24px] text-[#e1e1e1] max-w-[603px]"
              style={{ fontFamily: 'Inter, sans-serif' }}
            >
              Common questions, answered. Platform, plans, AI, collaboration and support.
            </p>
          </div>

          {/* Search */}
          <div className="bg-white border border-[#d5d7da] rounded-[6px] shadow-[0px_1px_2px_0px_rgba(10,13,18,0.05)] flex items-center gap-[8px] px-[14px] py-[10px] w-[449px] max-w-full">
            <svg className="w-[20px] h-[20px] text-[#71717a] shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
            <input
              type="text"
              placeholder="Search FAQs"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="flex-1 text-[16px] leading-[24px] text-[#71717a] placeholder:text-[#71717a] outline-none bg-transparent"
              style={{ fontFamily: 'Inter, sans-serif' }}
            />
          </div>
        </motion.div>
      </section>

      {/* ─── Tabs ─── */}
      <PlaybookTabs />

      {/* ─── FAQ Content ─── */}
      <section className="w-full bg-white px-6 md:px-[112px] py-[96px]">
        <div className="flex gap-[64px] items-start">

          {/* Sidebar */}
          {!searchQuery && (
            <aside className="w-[280px] shrink-0 flex flex-col gap-[16px]">
              {SIDEBAR_CATEGORIES.map((cat) => (
                <div key={cat.label} className="flex flex-col gap-[16px]">
                  <p
                    className="text-[14px] leading-[20px] font-bold text-[#020617] tracking-[-0.084px]"
                    style={{ fontFamily: "'Plus Jakarta Sans', sans-serif" }}
                  >
                    {cat.label}
                  </p>
                  <div className="flex flex-col">
                    {cat.items.map((item) => {
                      const isActive = activeCategory === item
                      return (
                        <button
                          key={item}
                          onClick={() => handleCategoryChange(item)}
                          className={`flex items-center min-h-[48px] px-[16px] py-[12px] border-l-2 transition-colors text-left w-full ${
                            isActive
                              ? 'border-[#020617] bg-white'
                              : 'border-[#cbd5e1] bg-white hover:border-[#94a3b8]'
                          }`}
                        >
                          <span
                            className={`text-[16px] leading-[22px] tracking-[-0.112px] ${
                              isActive ? 'font-semibold text-[#1e293b]' : 'font-medium text-[#475569]'
                            }`}
                            style={{ fontFamily: 'Inter, sans-serif' }}
                          >
                            {item}
                          </span>
                        </button>
                      )
                    })}
                  </div>
                </div>
              ))}
            </aside>
          )}

          {/* FAQ list */}
          <div className={`flex flex-col gap-[16px] ${searchQuery ? 'w-full' : 'flex-1 min-w-0'}`}>
            {filteredFaqs.length === 0 ? (
              <p
                className="text-[16px] text-[#475569] py-[40px] text-center"
                style={{ fontFamily: 'Inter, sans-serif' }}
              >
                No FAQs found for your search.
              </p>
            ) : (
              filteredFaqs.map((faq, i) => {
                const isOpen = !!openIds[faq.id]
                const isDark = faq.defaultOpen && isOpen && !searchQuery

                return (
                  <motion.div
                    key={faq.id}
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.3, delay: i * 0.04 }}
                    className={`rounded-[12px] overflow-hidden ${
                      isDark
                        ? 'bg-[#09090b] p-[24px]'
                        : 'border border-[#c6c8d0] p-[20px]'
                    }`}
                  >
                    <button
                      onClick={() => toggleFaq(faq.id)}
                      className="w-full flex items-start gap-[24px] text-left"
                    >
                      <span
                        className={`flex-1 text-[18px] leading-[28px] font-medium ${
                          isDark ? 'text-white' : 'text-black'
                        }`}
                        style={{ fontFamily: 'Inter, sans-serif' }}
                      >
                        {faq.question}
                      </span>
                      <span className={`mt-[4px] ${isDark ? 'text-white' : 'text-[#475569]'}`}>
                        <ChevronIcon open={isOpen} />
                      </span>
                    </button>

                    <AnimatePresence initial={false}>
                      {isOpen && (
                        <motion.div
                          key="content"
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: 'auto', opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          transition={{ duration: 0.25, ease: 'easeInOut' }}
                          className="overflow-hidden"
                        >
                          <div className="pt-[12px]">{faq.answer}</div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </motion.div>
                )
              })
            )}
          </div>
        </div>
      </section>
    </>
  )
}
