import api from '../../lib/api'
import { API_BASE_URL, ENDPOINTS } from '../config'

const DEFAULT_PLATFORM_HEALTH_DATA = {
  header: {
    title: 'Platform Health',
    subtitle: 'Engineering and reliability visibility — API performance, queues, logs, and real-time alerts.',
  },
  apiPercentiles: {
    title: 'API Response Time',
    p50: 94,
    p95: 312,
    p99: 680,
    status: 'healthy',
    statusLabel: 'Healthy',
    period: 'Last 24h · all endpoints',
  },
  errorRate: {
    title: 'Error Rate',
    value: '0.42%',
    change: '+0.08%',
    period: 'vs last 24h',
    status: 'warning',
    statusLabel: 'Elevated',
  },
  timeoutRate: {
    title: 'Timeout Rate',
    value: '0.18%',
    change: '-0.04%',
    period: 'vs last 24h',
    status: 'healthy',
    statusLabel: 'Normal',
  },
  uptime: {
    title: 'Uptime (30d)',
    value: '99.98%',
    change: '+0.01%',
    period: 'vs last month',
    status: 'healthy',
    statusLabel: 'Healthy',
  },
  endpointPerformance: {
    title: 'Endpoint Performance',
    rows: [
      { id: 'ep-1', endpoint: '/api/ai/generate', method: 'POST', p50: 820, p95: 4200, p99: 8900, errorRate: 0.61, callsPerHour: 3840, status: 'healthy' },
      { id: 'ep-2', endpoint: '/api/deck/generate', method: 'POST', p50: 1140, p95: 5800, p99: 12400, errorRate: 1.82, callsPerHour: 1220, status: 'degraded' },
      { id: 'ep-3', endpoint: '/api/rewrite/stream', method: 'POST', p50: 310, p95: 980, p99: 2100, errorRate: 0.34, callsPerHour: 5670, status: 'healthy' },
      { id: 'ep-4', endpoint: '/api/auth/me', method: 'GET', p50: 42, p95: 88, p99: 140, errorRate: 0.02, callsPerHour: 18400, status: 'healthy' },
      { id: 'ep-5', endpoint: '/api/vaults', method: 'GET', p50: 78, p95: 194, p99: 380, errorRate: 0.08, callsPerHour: 9200, status: 'healthy' },
      { id: 'ep-6', endpoint: '/api/exports/queue', method: 'POST', p50: 240, p95: 1800, p99: 4200, errorRate: 0.44, callsPerHour: 620, status: 'healthy' },
      { id: 'ep-7', endpoint: '/api/admin/overview', method: 'GET', p50: 190, p95: 520, p99: 940, errorRate: 0.00, callsPerHour: 280, status: 'healthy' },
      { id: 'ep-8', endpoint: '/api/style-guides', method: 'GET', p50: 55, p95: 120, p99: 220, errorRate: 0.00, callsPerHour: 1840, status: 'healthy' },
    ],
  },
  monitoring: {
    queue: {
      title: 'Queue Delays',
      value: '1.4',
      unit: 's avg',
      status: 'healthy',
      statusLabel: 'Normal',
      period: 'Last 1h · all queues',
      subRows: [
        { label: 'Export queue', value: 2.1, unit: 's', max: 10, status: 'healthy' },
        { label: 'AI job queue', value: 4.8, unit: 's', max: 10, status: 'warning' },
        { label: 'Notification queue', value: 0.3, unit: 's', max: 10, status: 'healthy' },
      ],
    },
    exports: {
      title: 'Export Processing Time',
      value: '8.2',
      unit: 's avg',
      status: 'healthy',
      statusLabel: 'Normal',
      period: 'Last 1h · all export types',
      subRows: [
        { label: 'PDF export', value: 6.4, unit: 's', max: 30, status: 'healthy' },
        { label: 'PPTX export', value: 11.8, unit: 's', max: 30, status: 'healthy' },
        { label: 'DOCX export', value: 5.2, unit: 's', max: 30, status: 'healthy' },
        { label: 'XLSX export', value: 9.4, unit: 's', max: 30, status: 'healthy' },
      ],
    },
  },
  systemLogs: {
    title: 'System Logs',
    incidents: [
      {
        id: 'inc-1',
        title: 'Elevated p95 latency on /deck/generate',
        severity: 'Critical',
        status: 'Active',
        service: 'Deck API',
        timestamp: 'Apr 21, 11:42 UTC',
        duration: 'Ongoing (38 min)',
        detail: 'p95 response time at 5.8s vs 2s SLA. Correlated with upstream GPT-4o provider degradation. On-call notified. Mitigation: routing to fallback cluster.',
      },
      {
        id: 'inc-2',
        title: '500 error spike on /rewrite/stream',
        severity: 'High',
        status: 'Investigating',
        service: 'Rewrite API',
        timestamp: 'Apr 21, 09:18 UTC',
        duration: '22 min',
        detail: 'Error rate peaked at 1.4%. Root cause identified: OpenAI rate limit on shared API key. Fix: rotated to dedicated key pool. Monitoring for recurrence.',
      },
      {
        id: 'inc-3',
        title: 'Auth service — login success rate dropped',
        severity: 'Medium',
        status: 'Resolved',
        service: 'Auth Service',
        timestamp: 'Apr 20, 22:05 UTC',
        duration: '8 min',
        detail: 'Google OAuth provider returned 503 for 8 minutes. Auto-recovered. Affected ~140 login attempts. Users prompted to retry.',
      },
      {
        id: 'inc-4',
        title: 'Export queue backlog exceeded threshold',
        severity: 'Low',
        status: 'Resolved',
        service: 'Exports',
        timestamp: 'Apr 20, 14:37 UTC',
        duration: '14 min',
        detail: 'Queue depth reached 340 jobs (threshold: 200). Worker pool auto-scaled from 4 to 10 nodes. Queue drained within SLA.',
      },
    ],
    deploys: [
      {
        id: 'dep-1',
        version: 'v2.14.3',
        title: 'Fix: Deck generation timeout handling + fallback model routing',
        status: 'success',
        author: 'Lena Fischer',
        timestamp: 'Apr 21, 08:00 UTC',
        tags: ['hotfix', 'ai', 'deck'],
      },
      {
        id: 'dep-2',
        version: 'v2.14.2',
        title: 'Feature: Export queue priority lanes + PPTX concurrency boost',
        status: 'success',
        author: 'Marcus Osei',
        timestamp: 'Apr 20, 16:30 UTC',
        tags: ['feature', 'exports', 'performance'],
      },
      {
        id: 'dep-3',
        version: 'v2.14.1',
        title: 'Fix: Auth token refresh race condition on concurrent tab reload',
        status: 'success',
        author: 'Priya Nair',
        timestamp: 'Apr 19, 12:15 UTC',
        tags: ['bugfix', 'auth'],
      },
      {
        id: 'dep-4',
        version: 'v2.14.0',
        title: 'Release: Realtime collaboration cursor sync + Yjs conflict resolution',
        status: 'success',
        author: 'Kwame Boateng',
        timestamp: 'Apr 18, 10:00 UTC',
        tags: ['release', 'collab', 'yjs'],
      },
      {
        id: 'dep-5',
        version: 'v2.13.9',
        title: 'Chore: Dependency upgrades + Tailwind 4 migration',
        status: 'rollback',
        author: 'CI / CD Pipeline',
        timestamp: 'Apr 17, 14:20 UTC',
        tags: ['chore', 'deps'],
      },
    ],
    releases: [
      {
        id: 'rel-1',
        version: 'v2.14.0',
        title: 'Realtime collaboration cursor sync',
        timestamp: 'Apr 18, 10:00 UTC',
        impact: 'Positive',
        metrics: [
          { label: 'Session length', value: '+18%' },
          { label: 'Collab usage', value: '+34%' },
          { label: 'Error rate', value: '−0.2%' },
          { label: 'CSAT', value: '+0.4 pts' },
        ],
      },
      {
        id: 'rel-2',
        version: 'v2.13.8',
        title: 'AI Deck generation — streaming output',
        timestamp: 'Apr 14, 09:00 UTC',
        impact: 'Positive',
        metrics: [
          { label: 'Completion rate', value: '+9%' },
          { label: 'Regen rate', value: '−0.3×' },
          { label: 'P95 latency', value: '−1.1s' },
          { label: 'Acceptance rate', value: '+6%' },
        ],
      },
      {
        id: 'rel-3',
        version: 'v2.13.5',
        title: 'Export pipeline rewrite (v2)',
        timestamp: 'Apr 10, 11:00 UTC',
        impact: 'Neutral',
        metrics: [
          { label: 'Export time', value: '−0.4s' },
          { label: 'Queue depth', value: '+12%' },
          { label: 'Error rate', value: '+0.1%' },
          { label: 'User reports', value: '3' },
        ],
      },
    ],
  },
  realtimeAlerts: {
    title: 'Real-Time System Alerts',
    alerts: [
      {
        id: 'rta-1',
        title: 'p95 latency breach — /deck/generate',
        severity: 'Critical',
        status: 'Active',
        service: 'Deck API',
        timestamp: 'Just now',
        description: 'p95 at 5.8s, breaching 2s SLA. On-call paged.',
        metric: 'p95: 5.8s',
      },
      {
        id: 'rta-2',
        title: 'AI job queue depth > 200 threshold',
        severity: 'High',
        status: 'Investigating',
        service: 'AI Queue',
        timestamp: '4 min ago',
        description: 'Queue depth at 248 jobs. Auto-scaling triggered.',
        metric: '248 jobs queued',
      },
      {
        id: 'rta-3',
        title: 'Error rate spike — /rewrite/stream',
        severity: 'High',
        status: 'Acknowledged',
        service: 'Rewrite API',
        timestamp: '12 min ago',
        description: 'Error rate at 1.82%. Upstream rate-limit suspected.',
        metric: '1.82% error rate',
      },
      {
        id: 'rta-4',
        title: 'Export worker memory warning',
        severity: 'Medium',
        status: 'Acknowledged',
        service: 'Exports',
        timestamp: '28 min ago',
        description: 'Worker node memory at 87% capacity. No action yet required.',
        metric: '87% memory',
      },
      {
        id: 'rta-5',
        title: 'SSL certificate expiry in 14 days',
        severity: 'Low',
        status: 'Acknowledged',
        service: 'Infra',
        timestamp: '2 hours ago',
        description: 'api.manifestr.ai cert expires Apr 35. Auto-renewal scheduled.',
        metric: '14 days remaining',
      },
    ],
  },
  failuresAlerts: {
    title: 'Failures & Alerts',
    subtitle: 'Recent incidents across services',
    alerts: [
      {
        id: 'alert-1',
        service: 'Deck API',
        title: 'Elevated p95 latency on /deck/generate',
        severity: 'Critical',
        status: 'Active',
        timestamp: 'Apr 21, 11:42 UTC',
        description: 'Response time exceeded 2s threshold on 3.2% of requests over a 15 min window.',
      },
      {
        id: 'alert-2',
        service: 'Rewrite API',
        title: '500 error spike on /rewrite/stream',
        severity: 'High',
        status: 'Investigating',
        timestamp: 'Apr 21, 09:18 UTC',
        description: 'Error rate rose to 1.4% — linked to upstream model provider timeouts.',
      },
      {
        id: 'alert-3',
        service: 'Auth Service',
        title: 'Login success rate dropped',
        severity: 'Medium',
        status: 'Resolved',
        timestamp: 'Apr 20, 22:05 UTC',
        description: 'Temporary OAuth provider degradation. Auto-recovered in 8 minutes.',
      },
      {
        id: 'alert-4',
        service: 'Exports',
        title: 'Queue backlog above threshold',
        severity: 'Low',
        status: 'Resolved',
        timestamp: 'Apr 20, 14:37 UTC',
        description: 'Worker pool scaled up; queue drained within SLA.',
      },
    ],
  },
}

export async function getAdminPlatformHealthData(params = {}) {
  try {
    const response = await api.get(ENDPOINTS.ADMIN.PLATFORM_HEALTH, {
      baseURL: API_BASE_URL,
      params,
    })

    return response?.data?.data || response?.data || DEFAULT_PLATFORM_HEALTH_DATA
  } catch (_error) {
    return DEFAULT_PLATFORM_HEALTH_DATA
  }
}

export { DEFAULT_PLATFORM_HEALTH_DATA }
